//
// Created by rucki on 6. 1. 2024.
//

#ifndef CLIENT_FARBY_H
#define CLIENT_FARBY_H
#include "winsock2.h"

const WORD zelena = FOREGROUND_GREEN | FOREGROUND_INTENSITY;
const WORD ruzova = FOREGROUND_RED | FOREGROUND_BLUE | FOREGROUND_INTENSITY;
const WORD modra = FOREGROUND_BLUE | FOREGROUND_INTENSITY;
const WORD cervena = FOREGROUND_RED | FOREGROUND_INTENSITY;
const WORD zlta = FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_INTENSITY;
const WORD tmavoSeda = FOREGROUND_INTENSITY;
const WORD svetloModra = FOREGROUND_BLUE | FOREGROUND_GREEN | FOREGROUND_INTENSITY;
const WORD tmavoModra = FOREGROUND_BLUE;
const WORD svetloZelena = FOREGROUND_GREEN | FOREGROUND_INTENSITY;
const WORD tmavoZelena = FOREGROUND_GREEN;
const WORD tmavoCervena = FOREGROUND_RED;
const WORD svetloZlta = FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_INTENSITY;
const WORD tmavoZlta = FOREGROUND_RED | FOREGROUND_GREEN;
const WORD tmavoRuzova = FOREGROUND_RED | FOREGROUND_BLUE;
const WORD svetloFialova = FOREGROUND_RED | FOREGROUND_BLUE | FOREGROUND_INTENSITY;
const WORD tmavoFialova = FOREGROUND_BLUE | FOREGROUND_INTENSITY;
const WORD biela = FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_BLUE | FOREGROUND_INTENSITY;
const WORD tmavoSiva = FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_BLUE;

#endif //CLIENT_FARBY_H
